#Doc : https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: tests workflow
on: push
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run test
      - run: npm run lint
      - run: git push --set-upstream origin tests-validation-branche